Basic installation framework

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,2 +1,21 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
+
+set -e
+
+if [ ! -n "$KATA" ]; then
+    KATA=~/.codekata
+fi
+
+if [ -d "$KATA" ]; then
+    echo "\033[0;33mYou already have Code Kata installed.\033[0m You'll need to remove $KATA if you want to (re)install"
+    exit
+fi
+
+echo "\033[0;34mCloning Code Kata repository...\033[0m"
+hash git >/dev/null 2>&1 && /usr/bin/env git clone https://github.com/grahambrooks/codekata.git $KATA || {
+  echo "installation failed (git not installed). Please install git and try again"
+  exit
+}
+
+ln -s "$KATA/scripts/codekata" "/usr/local/bin/codekata"
 
